project:
  type: website

website:
  title: "JR"
  site-url: https://jdnricardo.com
  favicon: favicon.svg
  navbar:
    left:
      - text: Posts
        href: blog.qmd
      - text: Consulting
        href: consulting.qmd
      - text: CV
        href: /assets/cv-julian-ricardo.pdf
    right:
      - icon: linkedin
        href: https://linkedin.com/in/julian-ricardo-388908a1
      - icon: github
        href: https://github.com/jdnricardo
      - icon: rss
        href: blog.xml
      - text: Archive
        href: archive.qmd 
cookie-consent: true        

format:
  html:
    theme: [journal, /styles/styles.scss]
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    scripts: 
      - /scripts/back-to-top.js



